# Generated by Django 3.2.6 on 2021-09-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicador',
            name='notas',
            field=models.TextField(default='nota por defecto', max_length=255),
            preserve_default=False,
        ),
    ]
