# Generated by Django 3.2.6 on 2021-09-08 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_publicador_notas'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='libro',
            table='libro',
        ),
        migrations.AlterModelTable(
            name='publicador',
            table='publicador',
        ),
    ]
